### ISSUE TITLE
ValueError running against geth

### ISSUE THREAD

**Issue by fvictorio** [banteg/gasprice#1]
I installed and executed `gasprice` against geth connected to the Rinkeby chain, and got this error:

```
[2017-12-28 18:34:13 -0300] [21425] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2017-12-28 18:34:13 -0300] [21425] [INFO] Starting worker [21425]
warming up  [------------------------------------]    1%
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/fvictorio/.local/lib/python3.5/site-packages/web3/utils/formatters.py", line 66, in apply_formatters_to_dict
    yield key, formatters[key](item)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/fvictorio/.local/lib/python3.5/site-packages/web3/middleware/pythonic.py", line 94, in to_hexbytes
    result, len(result), num_bytes
ValueError: The value HexBytes('0xd783010703846765746887676f312e392e32856c696e757800000000000000004a77407315bec04bc79b3093dc34e3417035e40731ddd3d859d9163142d5dd2c7bfb39dd963a9a542322d99621fd59145e25e58c5418d19d3a271bd3d0ef5d4b00') is 97 bytes, but should be 32
```

Am I doing something wrong here?

Thanks.

**Comment by banteg** [comment]
This looks like a problem with `web3py` library. It would be nice if you report it to them.
https://github.com/ethereum/web3.py
